version: '3'
services:
  neo4j_service:
    build: ./neo4j
    ports:
      - 7474:7474 # Neo4j Web UI
      - 7687:7687 # Neo4j API
    environment:
      NEO4J_AUTH: "neo4j/password"
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*"
    volumes:
      - ./data:/data
    networks:
      - graphrag_network
  #ollama_service:
  #  build: ./neo4j
  #  expose:
  #    - 11434 # Ollama API
  #  networks:
  #    - graphrag_network
  graphrag_service:
    image: graphrag_bim
    volumes: 
      - /home/fernando/dev:/home/ubuntu/dev
    tty: true
    stdin_open: true 
    network_mode: "host"
    ports:
      - 11434:11434 # Neo4j Web UI 
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: all # alternatively, use `count: all` for all GPUs
                capabilities: [gpu]
                
networks:
  graphrag_network:
    name: graphrag_network
