version: '3'
services:
  instance:
    image: graphrag_bim
    volumes: 
      - /home/fernando/dev:/home/ubuntu/dev
    tty: true
    stdin_open: true  
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: all # alternatively, use `count: all` for all GPUs
                capabilities: [gpu]
